const tg = window.Telegram?.WebApp;
if (tg) { tg.ready(); tg.expand(); tg.setHeaderColor('#0b0b0d'); tg.setBackgroundColor('#0b0b0d'); }

const DAY = 86400000;
const HOUR = 60 * 60 * 1000;
const bootNow = new Date();
const dateISO = (offset = 0) => new Date(bootNow.getTime() + offset * DAY).toISOString().slice(0,10);
const iconCategories = [
  ['guitar','Гитара','i-guitar'],['music','Музыка','i-music'],['mic','Микрофон','i-mic'],['drink','Посиделки','i-drink'],['chess','Шахматы','i-chess'],
  ['chat','Поговорить','i-chat'],['coffee','Кофе','i-coffee'],['game','Игры','i-game'],['art','Творчество','i-art'],['walk','Прогулка','i-walk'],
  ['sport','Спорт','i-sport'],['dog','С собакой','i-dog'],['study','Учёба','i-study'],['dating','Знакомства','i-heart'],['party','Вечеринка','i-party'],['other','Другое','i-other']
];
const categoryMap = Object.fromEntries(iconCategories.map(x => [x[0], {label:x[1], icon:x[2]}]));
const categoryColors={guitar:'#ff9f43',music:'#a66cff',mic:'#ff5f9e',drink:'#ff7a59',chess:'#59d8ff',chat:'#72e6a6',coffee:'#c89b6d',game:'#54a8ff',art:'#ff6fd8',walk:'#79e67b',sport:'#47d7ff',dog:'#f3c65b',study:'#8b8cff',dating:'#ff667d',party:'#ff4f8b',other:'#b7b7c2'};
function catStyle(key){return `style="--cat-color:${categoryColors[key]||categoryColors.other}"`;}

const seedEvents = [
  {id:'evt_1',title:'Играем на гитаре у Новой Голландии',category:'guitar',date:dateISO(0),time:'19:30',price:0,venue:'Новая Голландия',lat:59.9293,lng:30.2892,ageLimit:0,promoted:false,description:'Берём гитару, садимся на траве. Можно приходить со своим инструментом.',going:8,owner:false,type:'planned'},
  {id:'evt_2',title:'Хочу поболтать в Таврическом',category:'chat',date:dateISO(0),time:new Date().toTimeString().slice(0,5),price:0,venue:'Таврический сад',lat:59.9478,lng:30.3723,ageLimit:18,promoted:false,description:'Сижу у пруда ещё примерно час. Можно просто подойти познакомиться и поговорить.',going:2,owner:false,type:'instant',expiresAt:Date.now()+60*60*1000},
  {id:'evt_3',title:'Шахматы и кофе',category:'chess',date:dateISO(0),time:'18:00',price:0,venue:'Петроградская сторона',lat:59.9614,lng:30.3125,ageLimit:0,promoted:false,description:'Несколько досок, уровень любой. Кофе берём рядом.',going:11,owner:false,type:'planned'},
  {id:'evt_4',title:'Ночной квартирник на Лиговке',category:'music',date:dateISO(0),time:'21:00',price:500,venue:'Лиговский проспект',lat:59.9278,lng:30.3609,ageLimit:18,promoted:true,description:'Живой сет, небольшой бар и ограниченное количество мест.',going:34,owner:false,type:'planned'},
  {id:'evt_5',title:'Рисуем городской скетч',category:'art',date:dateISO(1),time:'17:30',price:0,venue:'Севкабель Порт',lat:59.9241,lng:30.2417,ageLimit:0,promoted:false,description:'Берите скетчбук. Рисуем город и знакомимся.',going:15,owner:false,type:'planned'},
  {id:'evt_6',title:'Фрисби после работы',category:'sport',date:dateISO(3),time:'19:00',price:0,venue:'Парк 300-летия',lat:59.9827,lng:30.1992,ageLimit:0,promoted:false,description:'Обычная дружеская игра, без подготовки.',going:6,owner:false,type:'planned'},
  {id:'evt_7',title:'Техно-вечеринка',category:'party',date:dateISO(12),time:'23:00',price:1500,venue:'Обводный канал',lat:59.9139,lng:30.3467,ageLimit:18,promoted:true,description:'Два танцпола и локальные артисты.',going:87,owner:false,type:'planned'}
];
const concerts = [
  {id:'c1',artist:'Большой концерт · Artist A',date:new Date(bootNow.getTime()+42*DAY),venue:'СКА Арена',price:'от 2 900 ₽',genre:'pop',url:'https://example.com/?ref=tuda'},
  {id:'c2',artist:'Artist B · Live',date:new Date(bootNow.getTime()+97*DAY),venue:'А2',price:'от 3 500 ₽',genre:'rock',url:'https://example.com/?ref=tuda'},
  {id:'c3',artist:'Electronic Night · Artist C',date:new Date(bootNow.getTime()+166*DAY),venue:'Севкабель Порт',price:'от 2 400 ₽',genre:'electronic',url:'https://example.com/?ref=tuda'},
  {id:'c4',artist:'Artist D · Stadium Show',date:new Date(bootNow.getTime()+280*DAY),venue:'Газпром Арена',price:'от 4 900 ₽',genre:'pop',url:'https://example.com/?ref=tuda'}
];

const state = {
  events: JSON.parse(localStorage.getItem('tuda_events') || 'null') || seedEvents,
  going: new Set(JSON.parse(localStorage.getItem('tuda_going') || '[]')),
  time:'today', categories:new Set(), price:null, distance:0, query:'', selectedId:null, markers:[], userLocation:null, nearbyMode:false, eventType:'planned', concertGenre:'all', refCount:Number(localStorage.getItem('tuda_refCount')||0)
};
const user = tg?.initDataUnsafe?.user || {first_name:'Илья',username:'telegram_user'};
const startParam = tg?.initDataUnsafe?.start_param || new URLSearchParams(location.search).get('tgWebAppStartParam');
if (startParam?.includes('ref_') && !sessionStorage.getItem('tuda_refCounted')) { state.refCount++; localStorage.setItem('tuda_refCount',String(state.refCount)); sessionStorage.setItem('tuda_refCounted','1'); }

const map = L.map('map',{zoomControl:false,attributionControl:true}).setView([59.9343,30.3351],12);
map.attributionControl.setPrefix(false);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);
L.control.zoom({position:'topright'}).addTo(map);

const $ = id => document.getElementById(id);
const els = {sheet:$('eventSheet'),feed:$('feedList'),eventCount:$('eventCount'),empty:$('mapEmpty'),form:$('eventForm'),toast:$('toast'),search:$('searchInput'),filterModal:$('filterModal'),moderationModal:$('moderationModal'),detail:$('eventDetailView'),detailBody:$('eventDetailBody'),detailHero:$('eventDetailHero'),detailHeroIcon:$('eventDetailHeroIcon'),photoInput:$('eventPhotoInput'),photoPreview:$('photoPreview'),removePhotoBtn:$('removePhotoBtn'),nearbyBtn:$('nearbyFeedBtn')};
let pendingPhotoData='';
function svgIcon(id, cls=''){ return `<svg class="${cls}" viewBox="0 0 24 24"><use href="#${id}"/></svg>`; }
function persist(){ localStorage.setItem('tuda_events',JSON.stringify(state.events)); localStorage.setItem('tuda_going',JSON.stringify([...state.going])); }
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function parseEventDate(e){return new Date(`${e.date}T${e.time||'00:00'}:00`)}
function eventExpiresAt(e){const explicit=Number(e.expiresAt);return Number.isFinite(explicit)&&explicit>0?explicit:parseEventDate(e).getTime()+HOUR}
function isEventCurrent(e,now=Date.now()){const expiresAt=eventExpiresAt(e);return Number.isFinite(expiresAt)&&expiresAt>now}
function formatDate(e){if(e.type==='instant')return 'Сейчас';const d=e.date===dateISO(0)?'Сегодня':e.date===dateISO(1)?'Завтра':new Date(e.date+'T12:00').toLocaleDateString('ru-RU',{day:'numeric',month:'short'});return `${d}, ${e.time}`}
function kmBetween(a,b){const R=6371,rad=x=>x*Math.PI/180,dLat=rad(b[0]-a[0]),dLon=rad(b[1]-a[1]),la1=rad(a[0]),la2=rad(b[0]);const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
function isWithinTime(e){const n=new Date();if(!isEventCurrent(e,n.getTime()))return false;if(state.time==='now')return e.type==='instant';if(e.type==='instant'&&state.time==='today')return true;if(state.time==='today')return e.date===dateISO(0);if(state.time==='tomorrow')return e.date===dateISO(1);const days=(new Date(e.date+'T23:59')-n)/DAY;if(state.time==='week')return days>=0&&days<=7;if(state.time==='month')return days>=0&&days<=30;return true}
function filteredEvents(){const q=state.query.trim().toLowerCase();const list=state.events.filter(e=>{if(!isWithinTime(e))return false;if(state.categories.size&&!state.categories.has(e.category))return false;if(state.price==='free'&&Number(e.price)!==0)return false;if(state.price==='paid'&&Number(e.price)===0)return false;if(q&&!`${e.title} ${e.description} ${e.venue} ${categoryMap[e.category]?.label||''}`.toLowerCase().includes(q))return false;if(state.distance&&state.userLocation&&kmBetween(state.userLocation,[e.lat,e.lng])>state.distance)return false;if(state.nearbyMode&&state.userLocation&&kmBetween(state.userLocation,[e.lat,e.lng])>3)return false;return true});if(state.nearbyMode&&state.userLocation)return list.sort((a,b)=>kmBetween(state.userLocation,[a.lat,a.lng])-kmBetween(state.userLocation,[b.lat,b.lng]));return list.sort((a,b)=>Number(b.promoted)-Number(a.promoted)||parseEventDate(a)-parseEventDate(b))}
function markerIcon(e){const icon=categoryMap[e.category]?.icon||'i-other';const color=categoryColors[e.category]||categoryColors.other;return L.divIcon({className:'',html:`<div class="${e.promoted?'premium-marker':'regular-marker'}" style="--cat-color:${color}">${svgIcon(icon,'marker-svg')}</div>`,iconSize:e.promoted?[46,46]:[38,38],iconAnchor:e.promoted?[23,23]:[19,19]})}
function renderMap(){state.markers.forEach(m=>map.removeLayer(m));state.markers=[];const list=filteredEvents();els.empty.classList.toggle('hidden',list.length>0);list.forEach(e=>{const m=L.marker([e.lat,e.lng],{icon:markerIcon(e),bubblingMouseEvents:false}).addTo(map);m.on('click',()=>showEvent(e.id));state.markers.push(m)});renderFeed()}
function eventCoverClass(e){return `cover-${e.category||'other'}`}
function closeEventSheet(){state.selectedId=null;els.sheet.classList.add('hidden')}
function showEvent(id){const e=state.events.find(x=>x.id===id);if(!e)return;state.selectedId=id;map.panTo([e.lat,e.lng],{animate:true});const cat=categoryMap[e.category]||categoryMap.other;const photo=e.imageData?`<img class="event-sheet-cover-photo" src="${e.imageData}" alt="">`:'';els.sheet.innerHTML=`<button class="event-sheet-cover ${eventCoverClass(e)} ${e.imageData?'has-photo':''}" data-open-detail="${e.id}" type="button" aria-label="Открыть событие">${photo}<span class="event-sheet-cover-icon">${svgIcon(cat.icon)}</span><span class="event-sheet-cover-hint">Открыть событие</span></button><div class="sheet-row"><div class="event-type-icon" ${catStyle(e.category)}>${svgIcon(cat.icon)}</div><div class="event-main">${e.promoted?'<span class="badge">ПРЕМИУМ</span>':''}${e.type==='instant'?'<span class="badge live-badge">СЕЙЧАС</span>':''}<h3 class="event-title">${escapeHtml(e.title)}</h3><div class="event-meta">${formatDate(e)} · ${e.price?e.price+' ₽':'Бесплатно'}<br>${escapeHtml(e.venue)} · ${e.ageLimit}+</div></div></div><p class="event-meta">${escapeHtml(e.description||'')}</p><div class="actions"><button class="primary-btn" data-going="${e.id}">${state.going.has(e.id)?'Вы идёте':'Пойду'} · ${e.going+(state.going.has(e.id)?1:0)}</button><button class="secondary-btn" data-share="${e.id}">Поделиться</button></div>`;els.sheet.classList.remove('hidden');els.sheet.querySelector('[data-open-detail]').onclick=()=>openEventDetail(e.id);els.sheet.querySelector('[data-going]').onclick=()=>toggleGoing(e.id);els.sheet.querySelector('[data-share]').onclick=()=>shareEvent(e.id)}
function openEventDetail(id){const e=state.events.find(x=>x.id===id);if(!e)return;const cat=categoryMap[e.category]||categoryMap.other;els.detail.dataset.eventId=id;els.detailHero.className=`event-detail-hero ${eventCoverClass(e)} ${e.imageData?'has-photo':''}`;els.detailHero.querySelectorAll('.event-detail-photo').forEach(x=>x.remove());if(e.imageData){const img=document.createElement('img');img.className='event-detail-photo';img.src=e.imageData;img.alt='';els.detailHero.prepend(img)}els.detailHeroIcon.innerHTML=svgIcon(cat.icon);els.detailBody.innerHTML=`${e.promoted?'<span class="badge">ПРЕМИУМ</span>':''}${e.type==='instant'?'<span class="badge live-badge">СЕЙЧАС</span>':''}<h2>${escapeHtml(e.title)}</h2><div class="detail-meta-row"><span>${formatDate(e)}</span><span>${e.price?e.price+' ₽':'Бесплатно'}</span><span>${escapeHtml(e.venue)}</span><span>${e.ageLimit}+</span></div><div class="detail-section"><h3>О событии</h3><p>${escapeHtml(e.description||'Описание пока не добавлено.')}</p></div><div class="detail-section"><h3>Активность</h3><p>${escapeHtml(cat.label)} · ${e.going+(state.going.has(e.id)?1:0)} ${state.going.has(e.id)?'включая вас':''}</p></div><div class="detail-actions"><button class="primary-btn" data-detail-going="${e.id}">${state.going.has(e.id)?'Вы идёте':'Пойду'}</button><button class="secondary-btn" data-detail-share="${e.id}">Поделиться</button></div>`;els.detail.classList.remove('hidden');els.detail.setAttribute('aria-hidden','false');els.detailBody.querySelector('[data-detail-going]').onclick=()=>{toggleGoing(e.id);openEventDetail(e.id)};els.detailBody.querySelector('[data-detail-share]').onclick=()=>shareEvent(e.id);tg?.BackButton?.show?.()}
function closeEventDetail(){els.detail.classList.add('hidden');els.detail.setAttribute('aria-hidden','true');tg?.BackButton?.hide?.()}
function renderFeed(){const list=filteredEvents();els.eventCount.textContent=`${list.length}`;if(els.nearbyBtn){els.nearbyBtn.classList.toggle('active',state.nearbyMode);els.nearbyBtn.setAttribute('aria-pressed',String(state.nearbyMode));}els.feed.innerHTML=list.length?list.map(e=>{const c=categoryMap[e.category]||categoryMap.other;const dist=state.userLocation?kmBetween(state.userLocation,[e.lat,e.lng]):null;const distanceText=dist!==null?` · ${dist<1?Math.max(50,Math.round(dist*1000/50)*50)+' м':dist.toFixed(1)+' км'}`:'';return `<article class="feed-card ${e.promoted?'promoted':''}"><div class="activity-icon" ${catStyle(e.category)}>${svgIcon(c.icon)}</div><div>${e.promoted?'<span class="badge">ПРЕМИУМ</span>':''}${e.type==='instant'?'<span class="badge live-badge">СЕЙЧАС</span>':''}<h3>${escapeHtml(e.title)}</h3><p>${formatDate(e)} · ${e.price?e.price+' ₽':'Бесплатно'} · ${escapeHtml(e.venue)}${distanceText}<br>${escapeHtml(c.label)}</p><div class="mini-actions"><button data-map="${e.id}">На карте</button><button data-going="${e.id}">${state.going.has(e.id)?'Иду ✓':'Пойду'}</button></div></div></article>`}).join(''):`<div class="empty-feed">${state.nearbyMode?'Рядом пока нет подходящих событий. Попробуй другой фильтр или отключи «Рядом».':'Ничего не найдено.'}</div>`;els.feed.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>openOnMap(b.dataset.map));els.feed.querySelectorAll('[data-going]').forEach(b=>b.onclick=()=>toggleGoing(b.dataset.going))}
function toggleGoing(id){state.going.has(id)?state.going.delete(id):state.going.add(id);persist();renderFeed();if(state.selectedId===id)showEvent(id);updateProfile();tg?.HapticFeedback?.impactOccurred('light')}
function openOnMap(id){switchView('mapView');setTimeout(()=>showEvent(id),80)}
async function shareEvent(id){const bot='eventmap_demo_bot';const ref=user.id||'guest';const url=`https://t.me/${bot}?startapp=event_${id}_ref_${ref}`;const e=state.events.find(x=>x.id===id);const share=`https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent('Смотри событие: '+e.title)}`;if(tg?.openTelegramLink)tg.openTelegramLink(share);else if(navigator.share)await navigator.share({title:e.title,url});else toast('Ссылка: '+url)}
function switchView(viewId){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active-view',v.id===viewId));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===viewId));els.sheet.classList.add('hidden');const showSearch=['mapView','feedView'].includes(viewId);$('globalSearch').classList.toggle('hidden',!showSearch);document.querySelector('.time-filters').classList.toggle('hidden',!showSearch);if(viewId==='mapView')setTimeout(()=>map.invalidateSize(),60);if(viewId==='feedView')renderFeed();if(viewId==='concertsView')renderConcerts();if(viewId==='profileView')updateProfile()}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
map.on('click',()=>closeEventSheet());
$('eventDetailBack').onclick=closeEventDetail;
if(tg?.BackButton)tg.BackButton.onClick(()=>{if(!els.detail.classList.contains('hidden'))closeEventDetail()});

document.querySelectorAll('[data-time]').forEach(ch=>ch.addEventListener('click',()=>{state.time=ch.dataset.time;document.querySelectorAll('[data-time]').forEach(x=>x.classList.toggle('active',x===ch));els.sheet.classList.add('hidden');renderMap()}));
els.search.addEventListener('input',()=>{state.query=els.search.value;renderMap()});

function renderCategoryUI(){const picker=$('iconPicker');picker.innerHTML=iconCategories.map(([key,label,icon],i)=>`<button type="button" class="icon-choice ${i===0?'active':''}" ${catStyle(key)} data-pick="${key}" title="${label}" aria-label="${label}">${svgIcon(icon)}<span>${label}</span></button>`).join('');picker.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{picker.querySelectorAll('.icon-choice').forEach(x=>x.classList.toggle('active',x===b));$('categoryInput').value=b.dataset.pick});const filters=$('categoryFilters');filters.innerHTML=iconCategories.map(([key,label,icon])=>`<button type="button" class="category-filter" ${catStyle(key)} data-cat="${key}">${svgIcon(icon)}<span>${label}</span></button>`).join('');filters.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.categories.has(b.dataset.cat)?state.categories.delete(b.dataset.cat):state.categories.add(b.dataset.cat);b.classList.toggle('active');renderMap()})}
renderCategoryUI();

$('openFiltersBtn').onclick=()=>{els.filterModal.classList.remove('hidden');els.filterModal.setAttribute('aria-hidden','false')};document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=()=>{els.filterModal.classList.add('hidden');els.filterModal.setAttribute('aria-hidden','true')});document.querySelectorAll('[data-price]').forEach(b=>b.onclick=()=>{state.price=state.price===b.dataset.price?null:b.dataset.price;document.querySelectorAll('[data-price]').forEach(x=>x.classList.toggle('active',x.dataset.price===state.price));renderMap()});$('distanceFilter').onchange=e=>{state.distance=Number(e.target.value);if(state.distance&&!state.userLocation)requestLocation(false);renderMap()};$('resetFiltersBtn').onclick=()=>{state.categories.clear();state.price=null;state.distance=0;document.querySelectorAll('.category-filter,[data-price]').forEach(x=>x.classList.remove('active'));$('distanceFilter').value='0';renderMap()};

function requestLocation(center=true,onSuccess=null){if(!navigator.geolocation){toast('Геолокация недоступна');return}navigator.geolocation.getCurrentPosition(pos=>{state.userLocation=[pos.coords.latitude,pos.coords.longitude];if(center)map.setView(state.userLocation,14);L.circleMarker(state.userLocation,{radius:6,color:'#d8ff43',fillColor:'#d8ff43',fillOpacity:1,weight:2}).addTo(map);els.form.lat.value=state.userLocation[0].toFixed(6);els.form.lng.value=state.userLocation[1].toFixed(6);onSuccess?.();renderMap();toast('Геолокация определена')},()=>toast('Разреши доступ к геолокации, чтобы показать события рядом'))}
$('locationBtn').onclick=()=>requestLocation(true);$('useLocationBtn').onclick=()=>requestLocation(false);
if(els.nearbyBtn)els.nearbyBtn.onclick=()=>{if(state.nearbyMode){state.nearbyMode=false;renderFeed();return}const enableNearby=()=>{state.nearbyMode=true;renderFeed()};if(state.userLocation)enableNearby();else requestLocation(false,enableNearby)};

function setEventType(type){state.eventType=type;document.querySelectorAll('[data-event-type]').forEach(b=>b.classList.toggle('active',b.dataset.eventType===type));$('plannedFields').classList.toggle('hidden',type!=='planned');$('instantFields').classList.toggle('hidden',type!=='instant')}
document.querySelectorAll('[data-event-type]').forEach(b=>b.onclick=()=>setEventType(b.dataset.eventType));
els.form.date.min=dateISO(0);els.form.date.max=dateISO(30);els.form.date.value=dateISO(0);els.form.time.value='20:00';
function resetPhotoUI(){pendingPhotoData='';if(els.photoInput)els.photoInput.value='';if(els.photoPreview)els.photoPreview.innerHTML=svgIcon('i-plus');$('photoUploadTitle').textContent='Добавить фотографию';els.removePhotoBtn?.classList.add('hidden')}
function compressPhoto(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1280,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.78))};img.src=reader.result};reader.readAsDataURL(file)})}
if(els.photoInput)els.photoInput.addEventListener('change',async()=>{const file=els.photoInput.files?.[0];if(!file)return resetPhotoUI();if(!file.type.startsWith('image/')){toast('Выбери изображение');return resetPhotoUI()}if(file.size>12*1024*1024){toast('Файл слишком большой');return resetPhotoUI()}try{pendingPhotoData=await compressPhoto(file);els.photoPreview.innerHTML=`<img src="${pendingPhotoData}" alt="Предпросмотр фотографии">`;$('photoUploadTitle').textContent='Фотография добавлена';els.removePhotoBtn.classList.remove('hidden')}catch{toast('Не удалось обработать фотографию');resetPhotoUI()}});
els.removePhotoBtn?.addEventListener('click',resetPhotoUI);

const hardBlockPatterns=[/наркот|закладк|героин|кокаин|амфетамин|оружи|взрывчат|террор|экстрем|проституц|купить\s+паспорт|продам\s+паспорт/i];
const profanityPatterns=[/\b(хуй|хуя|хуе|пизд|ебан|ёбан|ебат|бляд|сука)\w*/i];
const suspiciousPatterns=[/без\s+правил/i,/секретн\w*\s+адрес/i,/только\s+налич/i,/100%\s+заработ/i,/лёгк\w*\s+деньг/i];
function moderate(text){if(hardBlockPatterns.some(r=>r.test(text)))return {status:'block',title:'Публикация отклонена',text:'Обнаружены признаки запрещённого или опасного содержания. В боевой версии такое событие не будет опубликовано.'};if(profanityPatterns.some(r=>r.test(text)))return {status:'review',title:'Нужно исправить текст',text:'В названии или описании обнаружена грубая лексика. Переформулируй текст — так карточка будет понятнее и аккуратнее.'};if(suspiciousPatterns.some(r=>r.test(text)))return {status:'review',title:'Нужна ручная проверка',text:'Система обнаружила формулировки, которые требуют проверки модератором. В боевой версии событие попадёт в очередь review.'};return {status:'ok',title:'Проверка пройдена',text:'Событие прошло автоматическую проверку и опубликовано в локальном MVP.'}}
function showModeration(result,onOk){$('moderationIcon').className=`moderation-icon ${result.status}`;$('moderationIcon').textContent=result.status==='ok'?'✓':result.status==='review'?'!':'×';$('moderationTitle').textContent=result.title;$('moderationText').textContent=result.text;els.moderationModal.classList.remove('hidden');$('moderationOkBtn').onclick=()=>{els.moderationModal.classList.add('hidden');onOk?.()}}

els.form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(els.form).entries());if(state.eventType==='planned'){const chosen=new Date(`${data.date}T12:00`);const max=new Date(`${dateISO(30)}T23:59`);if(chosen<new Date(`${dateISO(0)}T00:00`)||chosen>max)return showModeration({status:'block',title:'Дата вне диапазона',text:'Пользовательские события можно создавать только на ближайшие 30 дней.'})}const mod=moderate(`${data.title} ${data.description||''}`);if(mod.status!=='ok')return showModeration(mod);const event={id:`evt_${Date.now()}`,title:data.title.trim(),category:data.category,date:state.eventType==='instant'?dateISO(0):data.date,time:state.eventType==='instant'?new Date().toTimeString().slice(0,5):data.time,price:Number(data.price||0),venue:data.venue.trim(),lat:Number(data.lat),lng:Number(data.lng),ageLimit:Number(data.ageLimit||0),promoted:data.promoted==='on',description:(data.description||'').trim(),ticketUrl:data.ticketUrl||'',imageData:pendingPhotoData,going:0,owner:true,type:state.eventType,expiresAt:state.eventType==='instant'?Date.now()+Number(data.duration||60)*60*1000:null};state.events.unshift(event);persist();showModeration(mod,()=>{els.form.reset();resetPhotoUI();els.form.date.min=dateISO(0);els.form.date.max=dateISO(30);els.form.date.value=dateISO(0);els.form.time.value='20:00';$('categoryInput').value='guitar';document.querySelectorAll('.icon-choice').forEach((x,i)=>x.classList.toggle('active',i===0));setEventType('planned');renderMap();updateProfile();switchView('mapView');setTimeout(()=>{map.setView([event.lat,event.lng],14);showEvent(event.id)},100);tg?.HapticFeedback?.notificationOccurred('success')})});

function renderConcerts(){const list=concerts.filter(c=>state.concertGenre==='all'||c.genre===state.concertGenre);$('concertList').innerHTML=list.map(c=>`<article class="concert-card"><div class="concert-visual"><span class="badge">${c.genre.toUpperCase()}</span><strong>${escapeHtml(c.artist)}</strong></div><div class="concert-body"><div class="concert-meta">${c.date.toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})}<br>${escapeHtml(c.venue)}</div><div class="concert-bottom"><b>${c.price}</b><button data-buy="${c.id}">Купить билет ↗</button></div></div></article>`).join('');$('concertList').querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const c=concerts.find(x=>x.id===b.dataset.buy);if(tg?.openLink)tg.openLink(c.url);else window.open(c.url,'_blank')})}
document.querySelectorAll('[data-concert]').forEach(b=>b.onclick=()=>{state.concertGenre=b.dataset.concert;document.querySelectorAll('[data-concert]').forEach(x=>x.classList.toggle('active',x===b));renderConcerts()});

function updateProfile(){$('profileName').textContent=user.first_name||'Пользователь';$('profileUsername').textContent=user.username?'@'+user.username:'Telegram Mini App';$('avatar').textContent=(user.first_name||'П')[0].toUpperCase();$('goingStat').textContent=state.going.size;$('createdStat').textContent=state.events.filter(e=>e.owner).length;$('refStat').textContent=state.refCount}
$('resetBtn').onclick=()=>{localStorage.removeItem('tuda_events');localStorage.removeItem('tuda_going');localStorage.removeItem('tuda_refCount');location.reload()};
function toast(message){els.toast.textContent=message;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),1900)}


const MASCOT_URL="./chaika-main.png?rev=2";
const MASCOT_POINT_URL="./chaika-point.png?rev=2";
const onboardingSteps=[
  {kicker:'ЗНАКОМСТВО',title:'Покажу, как тут всё работает',text:'На карте — события вокруг тебя. Быстро покажу основные кнопки.',speech:'Йоу! Я Чайка',mascot:MASCOT_URL,button:'Начать'},
  {kicker:'КАРТА',title:'Смотри, что происходит рядом',text:'Тут события на карте. Нажимай на маркеры и выбирай, куда пойти.',speech:'Вот что рядом',mascot:MASCOT_URL,button:'Дальше'},
  {kicker:'ЛЕНТА',title:'Листай события списком',text:'В ленте удобно смотреть фото, расстояние, время и кто идёт.',speech:'Можно и так',mascot:MASCOT_URL,button:'Дальше'},
  {kicker:'СОЗДАТЬ',title:'Создай своё событие',text:'Нажми +, выбери иконку, добавь одно фото, место и время.',speech:'Теперь твоя очередь',mascot:MASCOT_POINT_URL,button:'Понял!'}
]
let onboardingStep=0;
const onboardingEl=$('onboarding'), onboardingDots=$('onboardingDots');
function renderOnboarding(){
  const step=onboardingSteps[onboardingStep], card=onboardingEl.querySelector('.onboarding-card');
  card.dataset.step=String(onboardingStep);
  $('onboardingKicker').textContent=step.kicker;$('onboardingTitle').textContent=step.title;$('onboardingText').textContent=step.text;$('onboardingSpeech').textContent=step.speech;
  const mascot=$('onboardingMascot'); if(mascot){ mascot.classList.remove('mascot-fallback'); mascot.style.display='block'; mascot.src=step.mascot; mascot.onload=()=>{ const fb=document.getElementById('mascotFallbackCard'); if(fb) fb.hidden=true; }; mascot.onerror=()=>{ mascot.classList.add('mascot-fallback'); mascot.style.display='none'; const fb=document.getElementById('mascotFallbackCard'); if(fb) fb.hidden=false; }; const fb=document.getElementById('mascotFallbackCard'); if(fb) fb.hidden=true; }
  $('onboardingNext').textContent=step.button;
  onboardingDots.innerHTML=onboardingSteps.map((_,i)=>`<button class="onboarding-dot ${i===onboardingStep?'active':''}" type="button" aria-label="Шаг ${i+1}"></button>`).join('');
  onboardingDots.querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{onboardingStep=i;renderOnboarding()});
}
function closeOnboarding(){localStorage.setItem('chaika_onboarding_clean_2','done');onboardingEl.classList.add('hidden');onboardingEl.setAttribute('aria-hidden','true');tg?.HapticFeedback?.impactOccurred('light')}
function showOnboarding(){onboardingStep=0;renderOnboarding();onboardingEl.classList.remove('hidden');onboardingEl.setAttribute('aria-hidden','false')}
$('onboardingNext')?.addEventListener('click',()=>{if(onboardingStep<onboardingSteps.length-1){onboardingStep++;renderOnboarding();tg?.HapticFeedback?.selectionChanged()}else closeOnboarding()});
$('onboardingSkip')?.addEventListener('click',closeOnboarding);$('onboardingSkipTop')?.addEventListener('click',closeOnboarding);
if(!localStorage.getItem('chaika_onboarding_clean_2'))setTimeout(showOnboarding,220);

renderMap();renderConcerts();updateProfile();
