import { createClient } from "npm:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const enc=new TextEncoder();
const reply=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"Content-Type":"application/json"}});
async function mac(key:Uint8Array,msg:string){const k=await crypto.subtle.importKey("raw",key,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",k,enc.encode(msg)));}
const hx=(b:Uint8Array)=>[...b].map(x=>x.toString(16).padStart(2,"0")).join("");
function eq(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
async function verify(raw:string){const token=Deno.env.get("TELEGRAM_BOT_TOKEN");if(!token)throw new Error("bot_not_configured");const p=new URLSearchParams(raw),hash=(p.get("hash")||"").toLowerCase(),auth=Number(p.get("auth_date")||0),now=Math.floor(Date.now()/1000);if(!hash)throw new Error("hash_missing");if(!auth||auth>now+300||now-auth>86400)throw new Error("init_data_expired");const chk=(drop=false)=>[...p.entries()].filter(([k])=>k!=="hash"&&(!drop||k!=="signature")).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join("\n");const secret=await mac(enc.encode("WebAppData"),token);let ok=eq(hx(await mac(secret,chk(false))),hash);if(!ok&&p.has("signature"))ok=eq(hx(await mac(secret,chk(true))),hash);if(!ok)throw new Error("signature_invalid");const u=JSON.parse(p.get("user")||"null");if(!u?.id)throw new Error("user_missing");return u;}
const eventFields='id,title,category,event_type,starts_at,expires_at,price_rub,venue,lat,lng,age_limit,description,ticket_url,image_url,promoted,moderation_status,going_count,created_at,source,source_url';
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return reply({ok:false,error:'method_not_allowed'},405);try{const body=await req.json(),u=await verify(String(body.initData||'')),uid=Number(u.id),action=String(body.action||'dashboard');const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
if(action==='register_referral'){const inviter=Number(body.inviterTelegramUserId||0);if(!Number.isFinite(inviter)||inviter<=0||inviter===uid)return reply({ok:true,registered:false});const {data:inviterUser}=await db.from('telegram_users').select('telegram_user_id').eq('telegram_user_id',inviter).maybeSingle();if(!inviterUser)return reply({ok:true,registered:false});const {error}=await db.from('referrals').insert({inviter_telegram_user_id:inviter,invited_telegram_user_id:uid});if(error&&error.code!=='23505')throw error;return reply({ok:true,registered:!error});}
if(action==='avatar'){const dataUrl=String(body.dataUrl||'');const m=dataUrl.match(/^data:(image\/(?:jpeg|png|webp));base64,(.+)$/);if(!m)return reply({ok:false,error:'invalid_image'},400);const bytes=Uint8Array.from(atob(m[2]),c=>c.charCodeAt(0));if(bytes.byteLength>3145728)return reply({ok:false,error:'image_too_large'},400);const ext=m[1]==='image/png'?'png':m[1]==='image/webp'?'webp':'jpg';const path=`${uid}/avatar.${ext}`;const {error:uploadError}=await db.storage.from('avatars').upload(path,bytes,{contentType:m[1],upsert:true,cacheControl:'3600'});if(uploadError)throw uploadError;const {data:publicData}=db.storage.from('avatars').getPublicUrl(path);const url=`${publicData.publicUrl}?v=${Date.now()}`;const {error:updateError}=await db.from('telegram_users').update({avatar_url:url,updated_at:new Date().toISOString()}).eq('telegram_user_id',uid);if(updateError)throw updateError;return reply({ok:true,avatar_url:url});}
if(action!=='dashboard')return reply({ok:false,error:'unknown_action'},400);const {data:profile,error:profileError}=await db.from('telegram_users').select('telegram_user_id,username,first_name,last_name,photo_url,avatar_url').eq('telegram_user_id',uid).maybeSingle();if(profileError)throw profileError;const {data:attendance,error:attendanceError}=await db.from('event_attendees').select('event_id,created_at').eq('telegram_user_id',uid).order('created_at',{ascending:false}).limit(200);if(attendanceError)throw attendanceError;const ids=(attendance||[]).map((x:any)=>x.event_id);let attending:any[]=[];if(ids.length){const {data,error}=await db.from('events').select(eventFields).in('id',ids);if(error)throw error;const order=new Map(ids.map((id:string,i:number)=>[id,i]));attending=(data||[]).sort((a:any,b:any)=>(order.get(a.id)??999)-(order.get(b.id)??999));}const {data:created,error:createdError}=await db.from('events').select(eventFields).eq('telegram_owner_id',uid).order('created_at',{ascending:false}).limit(200);if(createdError)throw createdError;const {data:refs,error:refsError}=await db.from('referrals').select('invited_telegram_user_id,created_at').eq('inviter_telegram_user_id',uid).order('created_at',{ascending:false}).limit(200);if(refsError)throw refsError;const invitedIds=(refs||[]).map((x:any)=>x.invited_telegram_user_id);let invitedUsers:any[]=[];if(invitedIds.length){const {data,error}=await db.from('telegram_users').select('telegram_user_id,username,first_name,last_name,photo_url,avatar_url').in('telegram_user_id',invitedIds);if(error)throw error;const byId=new Map((data||[]).map((x:any)=>[String(x.telegram_user_id),x]));invitedUsers=(refs||[]).map((r:any)=>({...byId.get(String(r.invited_telegram_user_id)),referred_at:r.created_at})).filter((x:any)=>x.telegram_user_id);}return reply({ok:true,profile,attending,created:created||[],referrals:invitedUsers,counts:{going:attending.length,created:(created||[]).length,referrals:invitedUsers.length}});}catch(e){const m=e instanceof Error?e.message:'profile_failed';const auth=m.includes('signature')||m.includes('init_data')||m==='hash_missing'||m==='user_missing';return reply({ok:false,error:m},auth?401:400);}});